### ISSUE TITLE
Error after updating to Ruby v3

### ISSUE THREAD

**Issue by dsfernandobond** [coorasse/heroku-api-postgres#17]
After updating to Ruby v3 I receive the following error: 

`Backup Failed: /app/vendor/bundle/ruby/3.0.0/gems/heroku-api-postgres-0.10.0/lib/heroku/api/postgres/client.rb:43:in 'build_uri': wrong number of arguments (given 2, expected 1) `

**Comment by coorasse** [comment]
Fixed in 0.12.0
