### ISSUE TITLE
 Heroku::Api::Postgres::Backups.wait can halt indefinitely if the backup fails

### ISSUE THREAD

**Issue by immerrr** [coorasse/heroku-api-postgres#4]
Hi,

I've only recently started approaching Ruby code, so I might be reading things wrongly here, but AFAICS the `wait` method of `Heroku::Api::Postgres::Backups` class
```ruby
def wait(app_id, backup_id, options = { wait_interval: 3 })
  while true do
    ...
    break if backup[:finished_at] && backup[:succeeded]
  ...
```
can block indefinitely if the backup did not succeed (`backup[:succeeded] == false`).

**Comment by coorasse** [comment]
Agree. I'll fix it ASAP

**Comment by coorasse** [comment]
This is fixed in the last version. Thanks!

**Comment by immerrr** [comment]
@coorasse any ETA on when I can take the fix for a spin?

**Comment by coorasse** [comment]
0.10.0 is released. some other things changed to support pro plans: https://github.com/coorasse/heroku-api-postgres/pull/3

**Comment by immerrr** [comment]
Ah sweet, it is indeed, thank you!

I was checking github releases and 0.9.1 was still the most recent one there and I figured there was something else to release along.
