### ISSUE TITLE
backup url always return oldest backup url

### ISSUE THREAD

**Issue by deepakmahakale** [coorasse/heroku-api-postgres#6]
I am trying to use this gem to download the Heroku Postgres backup and then upload it to s3. 
After uploading the backup for a few days I realize that every backup in the last few days has the same size. 

then I checked with the following  

    postgres_api_client = Heroku::Api::Postgres.connect_oauth('oauth-key-here')
    backups_client = postgres_api_client.backups
    backup_url = backups_client.url('app_name', 1)
    #=> {:expires_at=>"2019-04-01 19:58:16 +0000", :url=>"https://abcd.s3.amazonaws.com/abcdefghabcdefghabcdefghabcdefgh/2019-03-23T07%3A30%3A53Z/abcdefghabcdefghabcdefghabcdefghabcdefgh?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASDKASJDKAJSDLKAJSD%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190401T181234Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=abcdefghabcdefghabcdefghabcdefghabcdefgh"}

![image](https://user-images.githubusercontent.com/14993828/55352775-4430cd80-54df-11e9-8325-695bcd50a86d.png)

Let me know if I am missing something

**Comment by coorasse** [comment]
The second argument you pass to `backups_client.url('app_name', 1)` (so `1` in your case), is the backup num for which you want the url. You can retrieve this number from `backups = backups_client.list(app_id)` (you have a `num` attribute for each backup) or `backups = backups_client.info(app_id, backup_id)` where you pass the `backup_id` instead.

**Comment by deepakmahakale** [comment]
Thanks @coorasse for the reply. I figured that out and I am using the URL out of `list` output directly.

```ruby
backups = backups_client.list(app_id)
last_backup = backups.max_by { |bck| bck[:num] }
database_url = last_backup[:to_url]
```
It will be great if we can return the last backup url if I am not passing any value for `backup_id`

The same way heroku cli does. Or can create a new method altogether 

Something like this.
```ruby
backup_url = backups_client.latest_url('app_name')
```

**Comment by deepakmahakale** [comment]
Let me know if you want me to raise a pull request for it. I will be happy to contribute

**Comment by coorasse** [comment]
interesting feature. I am happy to introduce something like this. PR is welcome! 👍

**Comment by i5okie** [comment]
Looks like Heroku has broken this on their end. I can no longer get the url.
I now get `{:error=>{:status=>500}}` every time.

**Comment by tanuj-ahuja** [comment]
@i5okie Same problem. Can no longer get the url. Getting - `{:error=>{:status=>500}}`

**Comment by coorasse** [comment]
Regarding the 500 error, I'd keep the discussion on #11 . I close this issue, feel free to open a PR to implement `last_url`

**Comment by deepakmahakale** [comment]
@coorasse I have opened pull request #15. After watching this notification I realized I had done the changes but never opened the pull request. 

It's been 2 years let's see if the change is still valid and can be merged.
